table fact_shot

	column shot_id
		dataType: int64
		summarizeBy: none
		sourceColumn: shot_id

	column lot_id
		dataType: int64
		summarizeBy: none
		sourceColumn: lot_id

	column die_id
		dataType: int64
		summarizeBy: none
		sourceColumn: die_id

	column shift_id
		dataType: int64
		summarizeBy: none
		sourceColumn: shift_id

	column risk
		dataType: double
		summarizeBy: none
		sourceColumn: risk

	column label
		dataType: int64
		summarizeBy: none
		sourceColumn: label

	column flagged
		dataType: int64
		summarizeBy: none
		sourceColumn: flagged

	column outcome
		dataType: string
		summarizeBy: none
		sourceColumn: outcome

	column dominant_mechanism
		dataType: string
		summarizeBy: none
		sourceColumn: dominant_mechanism

	partition fact_shot = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(ExportFolder & "\fact_shot.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"shot_id", Int64.Type}, {"lot_id", Int64.Type}, {"die_id", Int64.Type}, {"shift_id", Int64.Type}, {"risk", type number}, {"label", Int64.Type}, {"flagged", Int64.Type}, {"outcome", type text}, {"dominant_mechanism", type text}})
				in
				    Typed

