table fact_cost_curve

	column threshold
		dataType: double
		summarizeBy: none
		sourceColumn: threshold

	column per_shot
		dataType: double
		summarizeBy: none
		sourceColumn: per_shot

	column escape_rate
		dataType: double
		summarizeBy: none
		sourceColumn: escape_rate

	column overkill_rate
		dataType: double
		summarizeBy: none
		sourceColumn: overkill_rate

	column alert_rate
		dataType: double
		summarizeBy: none
		sourceColumn: alert_rate

	partition fact_cost_curve = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(ExportFolder & "\fact_cost_curve.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"threshold", type number}, {"per_shot", type number}, {"escape_rate", type number}, {"overkill_rate", type number}, {"alert_rate", type number}})
				in
				    Typed

